# backend에서 개발하기 위해 필요한 docker-compose 파일
# backend폴더에서 docker-compose up -d으로 시작
services:
  db:
    image: mysql:8.4
    container_name: mysql_container
    restart: always
    env_file: # 기본은 명령을 내리는 현재 경로 .env를 읽어옴
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306" # host port: container port
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
