upstream fastapi_backend {
    server fastapi:8000; # 127.0.0.1 대신 도커 컴포즈 서비스명 사용
}

server {
    listen 80;
    server_name smishing-detect-kdt2.cloud;

    # HTTP to HTTPS Redirect
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name smishing-detect-kdt2.cloud;

    ssl_certificate /etc/letsencrypt/live/smishing-detect-kdt2.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/smishing-detect-kdt2.cloud/privkey.pem;

    # Frontend Static Files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Backend API Proxy
    location /api/ { # /api/ 폴더 경로만 매칭
        proxy_pass http://fastapi_backend/; # /api 경로 떼기
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
