upstream fastapi_backend {
    server fastapi:8000; # 127.0.0.1 대신 도커 컴포즈 서비스명 사용
}

upstream prometheus_backend {
    server prometheus:9090;
}

upstream grafana_backend {
    server grafana:3000;
}

server {
    listen 80;
    server_name smishing-detect-kdt2.cloud;

    # HTTP to HTTPS Redirect
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    # client하고는 http2 적용, 웹소켓은 내부적으로 http/1.1
    listen 443 ssl;

    http2 on; # Nginx 1.25.1 이상

    server_name smishing-detect-kdt2.cloud;

    ssl_certificate /etc/letsencrypt/live/smishing-detect-kdt2.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/smishing-detect-kdt2.cloud/privkey.pem;

    # Frontend Static Files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Backend API Proxy
    location /api/ { # /api/ 폴더 경로만 매칭
        proxy_pass http://fastapi_backend/; # /api 경로 떼기
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # prometheus reverse proxy
    location /prometheus/ {
        proxy_pass http://prometheus_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # grafana reverse proxy
    location /grafana/ {
        proxy_pass http://grafana_backend;

        # 웹소켓 지원 추가 for grafana
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
    }
}
# 이 파일은 자동적으로 http 블록안에 들어가게 include 되있음.
